/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Grefuwan
 */
public class VistaInscripciones extends javax.swing.JFrame {

    /**
     * Creates new form VistaInscripcionesSocioActividad
     */
    public VistaInscripciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Inscripciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_SocioSeleccionado = new javax.swing.JTextField();
        jComboBox_Alta = new javax.swing.JComboBox<>();
        jComboBox_Baja = new javax.swing.JComboBox<>();
        jButton_DarAltaInscripcion = new javax.swing.JButton();
        jButton_DarBajaInscripcion = new javax.swing.JButton();
        jButton_SalirInscripcion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_NumSocSeleccionado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Inscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Inscripciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 810, 286));

        jLabel1.setText("Socio:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        getContentPane().add(jTextField_SocioSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 295, -1));

        jComboBox_Alta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 124, -1));

        jComboBox_Baja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 124, -1));

        jButton_DarAltaInscripcion.setText("Dar de alta");
        jButton_DarAltaInscripcion.setActionCommand("DarAltaInscripcion");
        getContentPane().add(jButton_DarAltaInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        jButton_DarBajaInscripcion.setText("Dar de baja");
        jButton_DarBajaInscripcion.setActionCommand("DarBajaInscripcion");
        getContentPane().add(jButton_DarBajaInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        jButton_SalirInscripcion.setText("Salir");
        jButton_SalirInscripcion.setActionCommand("Salir_Inscripcion");
        getContentPane().add(jButton_SalirInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, -1, -1));

        jLabel2.setText("Núm. Socio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));
        getContentPane().add(jTextField_NumSocSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 295, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInscripciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_DarAltaInscripcion;
    public javax.swing.JButton jButton_DarBajaInscripcion;
    public javax.swing.JButton jButton_SalirInscripcion;
    public javax.swing.JComboBox<String> jComboBox_Alta;
    public javax.swing.JComboBox<String> jComboBox_Baja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_Inscripciones;
    public javax.swing.JTextField jTextField_NumSocSeleccionado;
    public javax.swing.JTextField jTextField_SocioSeleccionado;
    // End of variables declaration//GEN-END:variables
}
