/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package pframe;


/**
 *
 * @author Grefuwan
 */
public class EjemploFrameApp extends java.awt.Frame {

    /**
     * Creates new form EjemploFrameApp
     */
    public EjemploFrameApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Salir = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(200, 300));
        setSize(new java.awt.Dimension(600, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        add(jButton_Salir, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        System.out.println("Le has dado al botón de salir");
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    /**
     * @param args the command line arguments
     *
     * @throws java.lang.Exception
     */
    public static void main(String args[]) throws Exception {

        int alto = 400, ancho = 600;

        EjemploFrameApp frame = new EjemploFrameApp();
        MiCanvas cv = new MiCanvas(ancho, alto);

        //Lo pongo visible
        frame.setVisible(true);
        frame.setSize(ancho, alto);
        frame.setLocation(200, 100);    //Hace que se ponga 200-> 100↓
        frame.setTitle("Ejemplo de Frame");
        frame.add(cv);  //Añado el canvas

        Recurso r = new Recurso(cv);

        //Sumador s1 = new Sumador(r, 0);
        Thread h1 = new Thread(new Sumador(r, 0));  //Le tengo que pasar el runnable
        Thread h2 = new Thread(new Sumador(r, 1));
        Thread h3 = new Thread(new Sumador(r, 1));

        //Lanzo los 3 hilos
        h1.start();
        h2.start();
        h3.start();

        //Espero a que acaben
        h1.join();
        h2.join();
        h3.join();

        
        //Pone en el Output los Contadores al final: 1-100 y 2-200
        int contadores[] = r.getContadores();
        System.out.println("Contador 1 - " + contadores[0]);
        System.out.println("Contador 2 - " + contadores[1]);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Salir;
    // End of variables declaration//GEN-END:variables
}

