package pcd_practica7;

import java.util.Random;

/**
 *
 * @author Grefuwan
 */
public class Frame_Generador extends java.awt.Frame {

    /**
     * Creates new form Frame_Generador
     */
    public Frame_Generador() {
        initComponents();
    }

    public static int numVehiculos = 10;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        int turnoVehiculo = 0;

        Random r = new Random();

        Thread[] vehiculo = new Thread[numVehiculos];

        Frame_Generador frame = new Frame_Generador();
        frame.setSize(1280, 768);
        MiCanvas cv = new MiCanvas(frame.getWidth(), frame.getHeight());
        Tunel t = new Tunel(cv);

        frame.add(cv);
        frame.setVisible(true);

        for (int i = 0; i < numVehiculos; i++) {
            turnoVehiculo = r.nextInt(10) + 1;

            if (turnoVehiculo < 4) {
                System.out.println("Crea Hilo Coche");
                vehiculo[i] = new Coche(i, t, cv);
            }

            else {
                System.out.println("Crea Hilo Furgo");
                vehiculo[i] = new Thread(new Furgo(i, t, cv));
            }

            vehiculo[i].start();
            Thread.sleep((r.nextInt(2) + 1) * 1000);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

