package amc_practica_2;

import Automatas.AFD;
import Automatas.AFND;
import Automatas.Transicion;
import Automatas.TransicionLambda;
import Grafo.GraphViz;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Garcia Villagran
 */
public class JFrame_AMC_P2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_AMC_P2
     */
    public JFrame_AMC_P2() {
        initComponents();
    }
    AFD automAFD;
    AFND automAFND;
    Fichero fich = new Fichero();
    int tipoAutomata;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Grafos = new javax.swing.JPanel();
        jButton_Archivo = new javax.swing.JButton();
        jPanel_AutomataTexto = new javax.swing.JPanel();
        jScrollPane_Automata = new javax.swing.JScrollPane();
        jTextArea_Automata = new javax.swing.JTextArea();
        jLabel_TipoAutomata = new javax.swing.JLabel();
        jButton_Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_CadenaTest = new javax.swing.JTextArea();
        jButton_ProbarCadena = new javax.swing.JButton();
        jLabel_ValidezCadena = new javax.swing.JLabel();
        jButton_Dibujar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Grafos.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel_GrafosLayout = new javax.swing.GroupLayout(jPanel_Grafos);
        jPanel_Grafos.setLayout(jPanel_GrafosLayout);
        jPanel_GrafosLayout.setHorizontalGroup(
            jPanel_GrafosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        jPanel_GrafosLayout.setVerticalGroup(
            jPanel_GrafosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        jButton_Archivo.setText("<html><center>Seleccionar<br>Archivo</center></html>");
        jButton_Archivo.setToolTipText("");
        jButton_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ArchivoActionPerformed(evt);
            }
        });

        jPanel_AutomataTexto.setBackground(new java.awt.Color(153, 153, 153));

        jTextArea_Automata.setColumns(20);
        jTextArea_Automata.setRows(5);
        jScrollPane_Automata.setViewportView(jTextArea_Automata);

        jLabel_TipoAutomata.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel_AutomataTextoLayout = new javax.swing.GroupLayout(jPanel_AutomataTexto);
        jPanel_AutomataTexto.setLayout(jPanel_AutomataTextoLayout);
        jPanel_AutomataTextoLayout.setHorizontalGroup(
            jPanel_AutomataTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AutomataTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Automata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_TipoAutomata, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_AutomataTextoLayout.setVerticalGroup(
            jPanel_AutomataTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AutomataTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AutomataTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AutomataTextoLayout.createSequentialGroup()
                        .addComponent(jLabel_TipoAutomata)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane_Automata, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        jTextArea_CadenaTest.setColumns(20);
        jTextArea_CadenaTest.setRows(5);
        jTextArea_CadenaTest.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea_CadenaTest);

        jButton_ProbarCadena.setText("Probar");
        jButton_ProbarCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProbarCadenaActionPerformed(evt);
            }
        });

        jButton_Dibujar.setText("<html><center>Dibujar<br>Autómata</center></html>");
        jButton_Dibujar.setToolTipText("");
        jButton_Dibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DibujarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Grafos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Dibujar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_AutomataTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_ProbarCadena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel_ValidezCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Grafos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Dibujar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(jPanel_AutomataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton_ProbarCadena)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_ValidezCadena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Salir)
                        .addGap(16, 16, 16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ArchivoActionPerformed
        File fichAutom = fich.seleccionaRutaArchivo();

        Object[] Automatas = {"AFD", "AFND"};
        tipoAutomata = JOptionPane.showOptionDialog(rootPane, "Seleccione si es AFD o AFND", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, Automatas, EXIT_ON_CLOSE);
        System.out.println("Tipo: " + tipoAutomata);
        try {
            switch (tipoAutomata) {
                case 0 -> {
                    automAFD = fich.ficheroCargaAFD(fichAutom);
                    jLabel_TipoAutomata.setText("Autómata AFD");
                    JOptionPane.showMessageDialog(rootPane, "Ha elegido AFD");
                    jTextArea_Automata.setText(automAFD.toString());
                }
                case 1 -> {
                    automAFND = fich.ficheroCargaAFND(fichAutom);
                    jLabel_TipoAutomata.setText("Autómata AFND");
                    JOptionPane.showMessageDialog(rootPane, "Ha elegido AFND");
                    jTextArea_Automata.setText(automAFND.toString());
                }
                default -> {
                    System.out.println("ERROR: JButton Cargar Archivo");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error en el formato del archivo");
            System.out.println("ERROR: Seleccionar Archivo");
        }
    }//GEN-LAST:event_jButton_ArchivoActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jButton_ProbarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProbarCadenaActionPerformed

        boolean validez;
        char[] cadenaChar = jTextArea_CadenaTest.getText().toCharArray();
        String[] cadenaString = new String[cadenaChar.length];
        for (int i = 0; i < cadenaChar.length; i++) {
            cadenaString[i] = String.valueOf(cadenaChar[i]);
        }
        switch (tipoAutomata) {
            case 0 ->
                validez = automAFD.reconocer(cadenaString);
            case 1 ->
                validez = automAFND.reconocer(cadenaString);
            default ->
                throw new AssertionError();
        }

        if (validez) {
            jLabel_ValidezCadena.setForeground(Color.green);
            jLabel_ValidezCadena.setText("Cadena Válida");
        }
        else {
            jLabel_ValidezCadena.setForeground(Color.red);
            jLabel_ValidezCadena.setText("Cadena Errónea");
        }
    }//GEN-LAST:event_jButton_ProbarCadenaActionPerformed

    private void jButton_DibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DibujarActionPerformed
        try {
            if (tipoAutomata == 0) {
                for (Transicion tran : automAFD.getListaTransiciones()) {
                    GraphViz.cargaTextoAFD(tran.getOrigen(), tran.getTransicion(), tran.getDestino().toString());
                }
                GraphViz.cargaEstadosAFD(automAFD);
                try {
                    GraphViz.generaDot(rootPane);
                } catch (InterruptedException ex) {
                    Logger.getLogger(JFrame_AMC_P2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else {
                for (Transicion tran : automAFND.getListaTransiciones()) {
                    System.out.println("Dibujar AFND: " + tran.getOrigen() + tran.getTransicion() + tran.getDestino());
                    GraphViz.cargaTextoAFNDNormal(tran.getOrigen(), tran.getTransicion(), tran.getDestino().toString());
                }
                for (TransicionLambda tran : automAFND.getTransicionesLambda()) {
                    GraphViz.cargaTextoAFNDLambda(tran.getOrigen(), "lambda", tran.getEstadosResultantes());
                }
                GraphViz.cargaEstadosAFND(automAFND);
                try {
                    GraphViz.generaDot(rootPane);
                } catch (InterruptedException ex) {
                    Logger.getLogger(JFrame_AMC_P2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            System.out.println("GeneraDot Main");

            //Dibujar Grafo
            Graphics dibujaLienzo = jPanel_Grafos.getGraphics();

            JFileChooser jfc = new JFileChooser();
            jfc.setCurrentDirectory(new java.io.File("C:\\Users\\" + System.getProperty("user.name") + "\\Desktop"));
            jfc.showOpenDialog(rootPane);

            BufferedImage image = ImageIO.read(new File(jfc.getSelectedFile().getAbsolutePath()));

            //dibujaLienzo.drawImage(image, 0, jPanel_Grafos.getHeight()/2, this);
            dibujaLienzo.drawImage(image, 0, 0, jPanel_Grafos.getWidth(), image.getHeight(), this);

        } catch (IOException ex) {
            Logger.getLogger(JFrame_AMC_P2.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_DibujarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JFrame_AMC_P2 jframe = new JFrame_AMC_P2();

        jframe.setSize(1000, 700);
        jframe.setTitle("AMC - Práctica 2");
        jframe.setLocation(75, 50);

        jframe.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Archivo;
    public javax.swing.JButton jButton_Dibujar;
    public javax.swing.JButton jButton_ProbarCadena;
    private javax.swing.JButton jButton_Salir;
    public javax.swing.JLabel jLabel_TipoAutomata;
    public javax.swing.JLabel jLabel_ValidezCadena;
    public javax.swing.JPanel jPanel_AutomataTexto;
    public javax.swing.JPanel jPanel_Grafos;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane_Automata;
    public javax.swing.JTextArea jTextArea_Automata;
    public javax.swing.JTextArea jTextArea_CadenaTest;
    // End of variables declaration//GEN-END:variables
}

