/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Grefuwan
 */
public class VistaSocios extends javax.swing.JPanel {

    /**
     * Creates new form VistaSocios
     */
    public VistaSocios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TablaSocios = new javax.swing.JTable();
        jLabel_NumSocio = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_DNI = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel_Correo = new javax.swing.JLabel();
        jLabel_FechaEntrada = new javax.swing.JLabel();
        jLabel_fechaNacimiento = new javax.swing.JLabel();
        jTextField_NumSocio = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_DNI = new javax.swing.JTextField();
        jTextField_Telefono = new javax.swing.JTextField();
        jTextField_Correo = new javax.swing.JTextField();
        jButton_Insertar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_VaciarTabla = new javax.swing.JButton();
        jButton_ListarSocios = new javax.swing.JButton();
        jLabel_Categoria = new javax.swing.JLabel();
        jTextField_Categoria = new javax.swing.JTextField();
        jDateChooser_FEntradaSocios = new com.toedter.calendar.JDateChooser();
        jDateChooser_FNac_Socios = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_TablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_TablaSocios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 860, 280));

        jLabel_NumSocio.setText("Número de Socio");
        add(jLabel_NumSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel_Nombre.setText("Nombre");
        add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel_DNI.setText("DNI");
        add(jLabel_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jLabel_telefono.setText("Teléfono");
        add(jLabel_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel_Correo.setText("Correo");
        add(jLabel_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, 29));

        jLabel_FechaEntrada.setText("Fecha de Entrada");
        add(jLabel_FechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, 29));

        jLabel_fechaNacimiento.setText("Fecha de Nacimiento");
        add(jLabel_fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, 18));
        add(jTextField_NumSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 200, -1));
        add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 200, -1));
        add(jTextField_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 200, -1));
        add(jTextField_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 200, -1));
        add(jTextField_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 200, -1));

        jButton_Insertar.setText("Insertar");
        jButton_Insertar.setActionCommand("InsertarSocio");
        add(jButton_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 110, -1));

        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.setActionCommand("ActualizarSocio");
        add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 110, -1));

        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.setActionCommand("EliminarSocio");
        add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 110, -1));

        jButton_VaciarTabla.setText("Vaciar Tabla");
        jButton_VaciarTabla.setActionCommand("VaciarTablaSocio");
        add(jButton_VaciarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 610, 120, -1));

        jButton_ListarSocios.setText("Listar Socios");
        jButton_ListarSocios.setActionCommand("ListarSocios");
        add(jButton_ListarSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 610, 150, -1));

        jLabel_Categoria.setText("Categoría");
        add(jLabel_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, 18));
        add(jTextField_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 200, -1));
        add(jDateChooser_FEntradaSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 200, -1));
        add(jDateChooser_FNac_Socios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 200, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Actualizar;
    public javax.swing.JButton jButton_Eliminar;
    public javax.swing.JButton jButton_Insertar;
    public javax.swing.JButton jButton_ListarSocios;
    public javax.swing.JButton jButton_VaciarTabla;
    public com.toedter.calendar.JDateChooser jDateChooser_FEntradaSocios;
    public com.toedter.calendar.JDateChooser jDateChooser_FNac_Socios;
    public javax.swing.JLabel jLabel_Categoria;
    public javax.swing.JLabel jLabel_Correo;
    public javax.swing.JLabel jLabel_DNI;
    public javax.swing.JLabel jLabel_FechaEntrada;
    public javax.swing.JLabel jLabel_Nombre;
    public javax.swing.JLabel jLabel_NumSocio;
    public javax.swing.JLabel jLabel_fechaNacimiento;
    public javax.swing.JLabel jLabel_telefono;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_TablaSocios;
    public javax.swing.JTextField jTextField_Categoria;
    public javax.swing.JTextField jTextField_Correo;
    public javax.swing.JTextField jTextField_DNI;
    public javax.swing.JTextField jTextField_Nombre;
    public javax.swing.JTextField jTextField_NumSocio;
    public javax.swing.JTextField jTextField_Telefono;
    // End of variables declaration//GEN-END:variables
}
