/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PCD_Practica3;

import java.awt.Color;
import static java.lang.Thread.*;

/**
 *
 * @author Grefuwan
 */
public class ColaFrame extends javax.swing.JFrame {

    /**
     * Creates new form ColaFrame
     */
    public ColaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     *
     * @throws java.lang.Exception
     *
     * Crea los objetos ColaFrame, ColaLenta, CanvasCola, y los hilos Productor
     * y Consumidor. Luego, lanzará ambos hilos, esperará a que terminen,
     * esperará 3 segundos y finalizará la ejecución
     */
    public static void main(String args[]) throws Exception {

        int alto = 400, ancho = 600;
        int capacidad = 4;

        ColaFrame clFrm = new ColaFrame();
        CanvasCola cnvsCl = new CanvasCola(capacidad, ancho, alto);

        //---Apartado Inicialización Frame---
        clFrm.setVisible(true);
        clFrm.setSize(ancho, alto);
        clFrm.setLocation(200, 100);
        clFrm.setTitle("Practica 3 PCD");
        clFrm.add(cnvsCl);

        //---Apartado Hilos---
        ColaLenta col = new ColaLenta(4, cnvsCl);

        Thread prod = new Thread(new Productor(1, col));
        Thread cons = new Thread(new Consumidor(1, col));

        prod.start();
        cons.start();

        prod.join();
        cons.join();

        System.out.println("Cola Final : " + col.toString());

        sleep(3000);

        System.out.println("P3 Terminada");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

